=== yashanmick/Expert-Systems/jess/Documentation/JessInAction/part7/xml/jess.dtd
<!-- XML DTD for Jess rules -->

<!ELEMENT rulebase (rule)*>
<!ELEMENT rule (lhs,rhs)>
<!ATTLIST rule name CDATA #REQUIRED priority CDATA "">

<!ELEMENT rhs (function-call)*>
<!ELEMENT lhs (group | pattern)*>

<!ELEMENT group (group | pattern)*>
<!ATTLIST group name CDATA #REQUIRED>

<!ELEMENT pattern (slot*)>
<!ATTLIST pattern name CDATA #REQUIRED binding CDATA "">

<!ELEMENT slot (variable | constant | function-call)*>
<!ATTLIST slot name CDATA #REQUIRED>

<!ELEMENT variable EMPTY>
<!ATTLIST variable name CDATA #REQUIRED>

<!ELEMENT function-call (head,(constant|variable|function-call)*)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT constant (#PCDATA)>

=== yashanmick/Expert-Systems/jess/Documentation/JessInAction/part7/xml/animal.xml
<?xml version="1.0"?>
<!DOCTYPE rulebase SYSTEM "jess.dtd">
<rulebase> 
  <rule name="AnimalRule1" priority="10">
    <lhs>
      <pattern name="animal" binding="animal">
        <slot name="has-hair">
          <constant>TRUE</constant>
        </slot>
      </pattern>
    </lhs>
    <rhs>
      <function-call>
        <head>modify</head>
        <variable>animal</variable>
        <constant>(type mammal)</constant>
      </function-call>
    </rhs>
  </rule>
</rulebase>

=== yashanmick/Expert-Systems/jess/Documentation/JessInAction/part7/xml/rule.xml
<?xml version="1.0"?>
<!DOCTYPE rulebase SYSTEM "jess.dtd">

  <rulebase> 
    <rule name="RuleName" priority="1">
      <lhs>
        <pattern name="number" binding="Y">
          <slot name="value">
            <variable name="x"/>    
            <function-call>
              <head>or</head>
              <function-call>
                <head>=</head>
                <variable name="x"/>
                <constant>2</constant>
              </function-call>
              <function-call>
                <head>=</head>
                <variable name="x"/>
                <constant>3</constant>
              </function-call>
            </function-call>
          </slot>
        </pattern>
        <group name="not">
          <pattern name="number">
            <slot name="value">
            <constant>3</constant>
            </slot>
          </pattern>
        </group>      
      </lhs>
      <rhs>    
        <function-call>
          <head>printout</head>
          <constant>t</constant>
          <variable name="x"/>
          <constant>crlf</constant>
        </function-call>
      </rhs>
    </rule>
  </rulebase>
